### ISSUE TITLE
[BUG] Automatic version updater not working

### ISSUE THREAD

**Issue by polyrain** [irishgreencitrus/godot-build-cli-go#11]
Currently, when you use the tool the latest version you can download and build on Raspberry Pi OS 64bit is 3.2.3, however the latest versions of Godot have increased since this. It would be great to get the ability to also build these versions.

**Comment by irishgreencitrus** [comment]
I'll add this now, however I'm going to be rewriting this tool as the codebase is messy and unsuitable for other things I want to add

**Comment by irishgreencitrus** [comment]
This should already be fixed by 210facdfaa9170785f8f71139842842b528b7a43

**Comment by irishgreencitrus** [comment]
> This should already be fixed by [210facd](https://github.com/irishgreencitrus/godot-build-cli-go/commit/210facdfaa9170785f8f71139842842b528b7a43)

Nevermind there's a bug in the implementation of this, just checked

**Comment by irishgreencitrus** [comment]
There's a bug in the way dependencies are setup in this repository, and I am unsure how to fix it. The best way is to clone this repository `git clone https://github.com/irishgreencitrus/godot-build-cli-go.git`, and in the directory just do `go install .`
you can then run by just doing `godot-build-cli-go` in any directory
